- name: Run Melon Radar
        uses: ./
        with:
          product-id: ${{ secrets.PERFORMANCE_ID }}
          schedule-id: ${{ secrets.SCHEDULE_ID }}
          telegram-bot-token: ${{ secrets.TELEGRAM_TOKEN }}
          telegram-chat-id: ${{ secrets.TELEGRAM_CHAT_ID }}
