name: workflow

on:
  push:
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1
      
      - name: Prepare
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Run Melon Bot
        run: node dist/index.js
        env:
          MELON_USER_ID: ${{ secrets.MELON_USER_ID }}
          MELON_USER_PASSWORD: ${{ secrets.MELON_USER_PASSWORD }}
          PERFORMANCE_ID: ${{ secrets.PERFORMANCE_ID }}
          PLAY_DATE: ${{ secrets.PLAY_DATE }}
          TICKET_COUNT: ${{ secrets.TICKET_COUNT }}
